### PR TITLE
Theme modern-lancer

### PR DESCRIPTION
**Pull request by softwarerero**
I derived modern-lancer from the modern theme and did some tweaks useful for freelancers. I'm not sure if this qualifies as a new theme, just sharing it in case it is useful for somebody, see it in action at http://softwarerero.com/.

### CODE REVIEW

**Comment by hacksalot** [comment]
Hey, awesome! Nice work. Will take a look and roll this in. Sorry for the delay, I/we normally try to respond to stuff within a day but you caught me during a move and relocation. Look for movement this weekend.

**Comment by hacksalot** [comment]
Are we still good to go here? Sorry for the delay.

**Comment by softwarerero** [comment]
I'm not sure how much progress fresh-themes made in the meantime, but I'm still here :-)

**Comment by hacksalot** [comment]
Glad to hear it. `fresh-themes` should get a boost here shortly, but in the meantime there's an opportunity to clean things up even if it introduces some breakage. HackMyResume CLI will be at 2.0.0 within the week and fresh-themes is moving to 1.0.0-beta ahead of the web version of HMR.

If you can [change the base branch][1] of this PR to `dev` we can get it into the sandbox immediately. We don't squash user contributions so you'll end up on master after we merge and release.

[1]: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by hacksalot** [comment]
Otherwise if it's a chore, or the branch has gotten stale etc., just leave it on `master` and we'll merge it here in a bit.

**Comment by softwarerero** [comment]
Changed base to dev

**Comment by hacksalot** [comment]
Nice work. Thanks for this. I'll follow up after tearing off some new tests and so forth feel free to submit new PRs if you add bells and whistles.

**Comment by hacksalot** [comment]
Test

**Comment by hacksalot** [comment]
Merged

**Pull request merged**
